@&AWRDIR/awrsnapdetails.sql
@&AWRDIR/awrhistcmdtypes.sql
@&AWRDIR/awrhistosstat.sql
@&AWRDIR/awrhistsysmetrichist.sql
@&AWRDIR/awrhistsysmetricsumm.sql
@&AWRDIR/dbahistsysstat.sql
@&AWRDIR/dbahistsystimemodel.sql
@&AWRDIR/ioevents.sql
@&AWRDIR/iofunction.sql
@&AWRDIR/sourceconn.sql
@&AWRDIR/sqlstats.sql
