@&EXTRACTSDIR/awrhistcmdtypes.sql
@&EXTRACTSDIR/awrhistosstat.sql
@&EXTRACTSDIR/awrhistsysmetrichist.sql
@&EXTRACTSDIR/awrhistsysmetricsumm.sql
@&EXTRACTSDIR/dbahistsysstat.sql
@&EXTRACTSDIR/dbahistsystimemodel.sql
@&EXTRACTSDIR/ioevents.sql
@&EXTRACTSDIR/iofunction.sql
@&EXTRACTSDIR/sourceconn.sql
@&EXTRACTSDIR/sqlstats.sql
