timeout: "1800s"
steps:
  # pull the existing image so we can utilize cache
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull us-central1-docker.pkg.dev/optimus-prime-ci/cloud-run-source-deploy/op-api:latest || exit 0",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/optimus-prime-ci/cloud-run-source-deploy/op-api:latest",
        "--cache-from",
        "us-central1-docker.pkg.dev/optimus-prime-ci/cloud-run-source-deploy/op-api:latest",
        ".",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: pip
    args: ["install", "-U", ".", "--user"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: python3
    args: ["-m", "invoke", "pull-config"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: python3
    args: ["-m", "invoke", "deploy", "--tag=latest"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: python3
    args: ["-m", "invoke", "test"]
images:
  - us-central1-docker.pkg.dev/optimus-prime-ci/cloud-run-source-deploy/op-api:latest
