version: "3.9"
services:
  cache:
    image: docker.io/library/redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - cache-data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped

  db:
    image: docker.io/library/postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "P455W0rD__1"
      POSTGRES_USER: "app"
      POSTGRES_DB: "dbma"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: dbma run server
  #   image: dbma:latest
  #   restart: always
  #   depends_on:
  #     - db
  #     - cache
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env.example
  #   volumes:
  #     - static-data:/workspace/app/static:cached
  #     - upload-data:/workspace/app/media:cached

  # migrator:
  #   image: dbma:latest
  #   restart: never
  #   command: dbma manage upgrade-database
  #   env_file:
  #     - .env.example
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  db-data: {}
  cache-data: {}
  static-data: {}
  upload-data: {}
