version: "3.9"
services:
  app:
    build:
      context: .
      target: build-stage
      dockerfile: ./Dockerfile
      args:
        # remove this to build for production.
        POETRY_INSTALL_ARGS: --with="docs,linting,test"
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace/app/
    command: poetry run dbma run server

  localmail:
    image: mailhog/mailhog:v1.0.0
    container_name: localmail
    ports:
      - "8025:8025"
      - "1025:1025"
