(
SELECT -1 OSSTAT_ID, 'N/A' STAT_NAME, 'NO' AS CUMULATIVE FROM DUAL UNION ALL
SELECT 0,'NUM_CPUS','NO' FROM DUAL UNION ALL
SELECT 1,'IDLE_TIME','YES' FROM DUAL UNION ALL
SELECT 2,'BUSY_TIME','YES' FROM DUAL UNION ALL
SELECT 3,'USER_TIME','YES' FROM DUAL UNION ALL
SELECT 4,'SYS_TIME','YES' FROM DUAL UNION ALL
SELECT 5,'IOWAIT_TIME','YES' FROM DUAL UNION ALL
SELECT 6,'NICE_TIME','YES' FROM DUAL UNION ALL
SELECT 14,'RSRC_MGR_CPU_WAIT_TIME','YES' FROM DUAL UNION ALL
SELECT 15,'LOAD','NO' FROM DUAL UNION ALL
SELECT 16,'NUM_CPU_CORES','NO' FROM DUAL UNION ALL
SELECT 17,'NUM_CPU_SOCKETS','NO' FROM DUAL UNION ALL
SELECT 20,'INST_TYPE','NO' FROM DUAL UNION ALL
SELECT 1008,'PHYSICAL_MEMORY_BYTES','NO' FROM DUAL UNION ALL
SELECT 1009,'VM_IN_BYTES','YES' FROM DUAL UNION ALL
SELECT 1010,'VM_OUT_BYTES','YES' FROM DUAL UNION ALL
SELECT 1011,'FREE_MEMORY_BYTES','NO' FROM DUAL UNION ALL
SELECT 1012,'INACTIVE_MEMORY_BYTES','NO' FROM DUAL UNION ALL
SELECT 1013,'SWAP_FREE_BYTES','NO' FROM DUAL UNION ALL
SELECT 2000,'TCP_SEND_SIZE_MIN','NO' FROM DUAL UNION ALL
SELECT 2001,'TCP_SEND_SIZE_DEFAULT','NO' FROM DUAL UNION ALL
SELECT 2002,'TCP_SEND_SIZE_MAX','NO' FROM DUAL UNION ALL
SELECT 2003,'TCP_RECEIVE_SIZE_MIN','NO' FROM DUAL UNION ALL
SELECT 2004,'TCP_RECEIVE_SIZE_DEFAULT','NO' FROM DUAL UNION ALL
SELECT 2005,'TCP_RECEIVE_SIZE_MAX','NO' FROM DUAL UNION ALL
SELECT 2006,'GLOBAL_SEND_SIZE_MAX','NO' FROM DUAL UNION ALL
SELECT 2007,'SELECT GLOBAL_RECEIVE_SIZE_MAX','NO' FROM DUAL) 
