SELECT a.ckey,
       a.db_name,
       a.dbid,
       a.dbversion,
       a.hour,
       a.source_db_size_allocated_tb,
       SUM(a.source_num_cpu_cores)             source_num_cpu_cores,
       SUM(a.source_host_cpu_utilization_perc) source_host_cpu_utilization_perc,
       SUM(a.source_db_cpu_utilization_perc)   source_db_cpu_utilization_perc,
       SUM(a.source_database_memory_gb)        source_database_memory_gb,
       SUM(a.source_io_rep_per_sec)            source_io_rep_per_sec,
       SUM(a.bms_host_machine_cores)           bms_host_machine_cores,
       SUM(a.bms_database_cores)               bms_database_cores,
       SUM(a.bms_database_memory_gb)           bms_database_memory_gb,
       SUM(a.bms_db_tb_disk_for_iops)          bms_db_tb_disk_for_iops,
       SUM(a.bms_est_monthly_storage_bill)     bms_est_monthly_storage_bill
FROM   mydataset.vbms_sizing_detailperpdb a
GROUP  BY a.ckey,
          a.db_name,
          a.dbid,
          a.dbversion,
          a.hour,
          a.source_db_size_allocated_tb; 
