\i sql/init.sql
\o output/opdb__pg_applications_:VTAG.csv
\i sql/applications.sql
\o output/opdb__pg_aws_extension_dependency_:VTAG.csv
\i sql/aws_extension_dependency.sql
\o output/opdb__pg_aws_oracle_exists_:VTAG.csv
\i sql/aws_oracle_exists.sql
--\o output/opdb__pg_aws_oracle_version_:VTAG.csv
--\i sql/aws_oracle_version.sql
\o output/opdb__pg_bg_writer_stats_:VTAG.csv
\i sql/bg_writer_stats.sql
\o output/opdb__pg_database_details_:VTAG.csv
\i sql/database_details.sql
\o output/opdb__pg_extensions_:VTAG.csv
\i sql/extensions.sql
\o output/opdb__pg_index_details_:VTAG.csv
\i sql/index_details.sql
\o output/opdb__pg_replication_slots_:VTAG.csv
\i sql/replication_slots.sql
\o output/opdb__pg_replication_stats_:VTAG.csv 
\i sql/replication_stats.sql
\o output/opdb__pg_settings_:VTAG.csv
\i sql/settings.sql
-- \o output/opdb__schema_objects_:VTAG.csv
-- \i sql/schema_objects.sql
\o output/opdb__pg_settings_:VTAG.csv
\i sql/settings.sql
\o output/opdb__table_details_:VTAG.csv
\i sql/table_details.sql
\o output/opdb__pg_version_:VTAG.csv
\i sql/version.sql