\i sql/init.sql
\i sql/applications.sql
--\i sql/awsextensiondependency.sql
--\i sql/awsoracleexists.sql
--\i sql/awsoracleversion.sql
\i sql/bgwriterstats.sql
\i sql/databasesize.sql
\i sql/extensions.sql
\i sql/indexdetail.sql
\i sql/indexiostats.sql
\i sql/relationsize.sql
\i sql/relationsizesummary.sql
\i sql/replicationslots.sql
\i sql/replicationstats.sql
\i sql/roles.sql
\i sql/settings.sql
\i sql/sproccount.sql
\i sql/tableiostats.sql
\i sql/tablesbyschema.sql
\i sql/version.sql
