-- Copyright 2024 Google LLC
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- Grants required permissions to an assessment user for DB2 collection
-- Replace <USERNAME> with the target database user.

GRANT CONNECT ON DATABASE TO USER <USERNAME>;

-- System Catalog Grants
GRANT SELECT ON TABLE SYSCAT.TABLES TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.COLUMNS TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.INDEXES TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.TABCONST TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.REFERENCES TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.ROUTINES TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.TRIGGERS TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.VIEWS TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.DATAPARTITIONS TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSCAT.CONTROLS TO USER <USERNAME>;

-- Administrative Views Grants
GRANT SELECT ON TABLE SYSIBMADM.DBCFG TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSIBMADM.DBMCFG TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSIBMADM.ENV_INST_INFO TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSIBMADM.ENV_SYS_INFO TO USER <USERNAME>;
GRANT SELECT ON TABLE SYSIBMADM.ENV_PROD_INFO TO USER <USERNAME>;

-- Performance and Monitoring Function Grants
GRANT EXECUTE ON FUNCTION SYSPROC.MON_GET_INSTANCE TO USER <USERNAME>;
GRANT EXECUTE ON FUNCTION SYSPROC.MON_GET_DATABASE TO USER <USERNAME>;
GRANT EXECUTE ON FUNCTION SYSPROC.MON_GET_TABLESPACE TO USER <USERNAME>;
GRANT EXECUTE ON FUNCTION SYSPROC.MON_GET_BUFFERPOOL TO USER <USERNAME>;
GRANT EXECUTE ON FUNCTION SYSPROC.MON_GET_TRANSACTION_LOG TO USER <USERNAME>;
GRANT EXECUTE ON FUNCTION SYSPROC.ENV_GET_INST_INFO TO USER <USERNAME>;
GRANT EXECUTE ON FUNCTION SYSPROC.ENV_GET_PROD_INFO TO USER <USERNAME>;
